(load "lib.scm")
;
(define (proc x y z)
        (if (> x y)
            (if (> y z)
                (+ (square x) (square y))
                (+ (square x) (square z)))
            (if (> x z)
                (+ (square x) (square y))
                (+ (square y) (square z)))))

(proc 1 2 3)
(proc 1 3 2)
(proc 2 1 3)
(proc 2 3 1)
(proc 3 1 2)
(proc 3 2 1)
(proc 1 2 2)
(proc 2 1 2)
(proc 2 2 1)
(proc 1 1 1)

