(define (cont-frac n d k)
  (define (cont-frac-sub curk)
    (if (= curk k)
        (/ (n curk) (d curk))
        (/ (n curk) (+ (d curk) (cont-frac-sub (+ curk 1))))))
  (cont-frac-sub 1))

(cont-frac (lambda (i) 1.0)
           (lambda (i)
                   (if (= (remainder i 3) 2)
                       (* (ceiling (/ i 3)) 2)
                       1))
           100)
