(define (mycons a b)
  (* (expt 2 a) (expt 3 b)))
(define (mycar z)
  (if (= (remainder z 2) 0)
      (+ (mycar (/ z 2)) 1)
      0))
(define (mycdr z)
  (if (= (remainder z 3) 0)
      (+ (mycdr (/ z 3)) 1)
      0))
(mycar (mycons 4 5))
(mycdr (mycons 4 5))
