(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
    (cond ((not (eq? p password)) (lambda (x) "Incorrect password"))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       m))))
  dispatch)

(define (make-joint account password new-password)
  (if (not (number? ((account password 'withdraw) 0)))
      (lambda (p m) (lambda (x) "Invalid account"))
      (lambda (p m) (if (not (eq? p new-password))
                        (lambda (x) "Incorrect password")
                        (account password m)))))

