(define inc add1)
(define dec sub1)
(define square sqr)
(define (cube x)  (* x x x))
(define (average x y)
  (/ (+ x y) 2))
(define (logt base x)
  (/ (log x) (log base)))
(define (log2 x)
  (logt 2 x))
